// @vitest-environment jsdom
import * as React from 'react';
import { render, screen, fireEvent, cleanup, waitFor } from '@testing-library/react';
import { afterEach, describe, it, expect, vi } from 'vitest';
import { FileShell } from '../file-shell';
import { FileVersionHistory, FileMetadata, FileShellPanels, FilePresence } from '../../ui/file-shell-controls';
import { FileHeader } from '../../ui/file-header';
import { expectA11yClean } from '../../test-support/ds-assert';
afterEach(cleanup);
const versions=[{id:'v1',label:'Checkpoint',revisionId:'r1',createdAt:null,creator:null,canonical:true}];
function Shell({read=true,write=true,comment=true,review=true}:{read?:boolean;write?:boolean;comment?:boolean;review?:boolean}){const [active,setActive]=React.useState<'comments'|'review'|null>(null);return <FileShell header={{title:'Proposal',fileTypeLabel:'HTML file',fileKind:'htmlFile'}} capabilities={{read,write,comment,review}} onRename={vi.fn()} participants={[]} panels={[{purpose:'comments',label:'Comments',content:<p>Thread content</p>},{purpose:'review',label:'Review',content:<p>Review content</p>}]} activePanel={active} onPanelChange={setActive} annotationMode="selectElement" onAnnotationModeChange={vi.fn()} commands={[]}><p>Protected content</p></FileShell>;}
describe('File shell integration contract',()=>{
 it('preserves panel and content focus on Escape without consuming the event',()=>{render(<Shell/>);fireEvent.click(screen.getByRole('button',{name:'Comments'}));const panel=screen.getByRole('complementary',{name:'Comments'});panel.focus();expect(fireEvent.keyDown(panel,{key:'Escape'})).toBe(true);expect(panel).toHaveFocus();const editor=document.createElement('div');editor.contentEditable='true';editor.tabIndex=0;document.querySelector('.weft-file-shell-content')!.append(editor);editor.focus();expect(fireEvent.keyDown(editor,{key:'Escape'})).toBe(true);expect(editor).toHaveFocus();expect(panel).toBeVisible();});
 it('keeps pointer focus on its rail control when toggled',()=>{render(<Shell/>);const trigger=screen.getByRole('button',{name:'Comments'});trigger.focus();fireEvent.pointerDown(trigger);fireEvent.click(trigger);expect(trigger).toHaveFocus();fireEvent.click(trigger);expect(trigger).toHaveFocus();expect(screen.queryByRole('complementary')).toBeNull();});
 it('does not move focus when a panel is supplied at mount',()=>{render(<FileShellPanels panels={[{purpose:'comments',label:'Comments',content:'Threads'}]} active="comments" onActiveChange={vi.fn()} label="Controls">Content</FileShellPanels>);expect(document.body).toHaveFocus();});
 it('includes visible overflow text in its accessible name',async()=>{const {container}=render(<FilePresence label="Participants" participants={Array.from({length:6},(_,i)=>({id:String(i),name:`Person ${i}`,initials:'P',kind:'human' as const}))}/>);expect(screen.getByRole('button',{name:'+3, show all 6 participants'})).toHaveTextContent('+3');await expectA11yClean(container,{rules:{'label-content-name-mismatch':{enabled:true}}});});
 it('moves focus into exclusive panels and closes with a second rail activation',()=>{render(<Shell/>);const comments=screen.getByRole('button',{name:'Comments'});fireEvent.click(comments);expect(screen.getByRole('complementary',{name:'Comments'})).toHaveFocus();fireEvent.click(screen.getByRole('button',{name:'Review'}));expect(screen.queryByRole('complementary',{name:'Comments'})).toBeNull();expect(screen.getByRole('complementary',{name:'Review'})).toHaveFocus();fireEvent.click(screen.getByRole('button',{name:'Review'}));expect(screen.queryByRole('complementary')).toBeNull();expect(screen.getByRole('button',{name:'Review'})).toHaveFocus();fireEvent.click(comments);fireEvent.click(comments);expect(screen.queryByRole('complementary')).toBeNull();expect(comments).toHaveFocus();});
 it('returns focus to the current rail purpose after a programmatic switch',()=>{const change=vi.fn();const panels=[{purpose:'comments' as const,label:'Comments',content:<p>Threads</p>},{purpose:'versionHistory' as const,label:'Version history',content:<p>Versions</p>}];const {rerender}=render(<FileShellPanels panels={panels} active={null} onActiveChange={change} label="File side controls">Content</FileShellPanels>);fireEvent.click(screen.getByRole('button',{name:'Comments'}));rerender(<FileShellPanels panels={panels} active="comments" onActiveChange={change} label="File side controls">Content</FileShellPanels>);expect(screen.getByRole('button',{name:'Version history'})).not.toHaveAttribute('aria-controls');rerender(<FileShellPanels panels={panels} active="versionHistory" onActiveChange={change} label="File side controls">Content</FileShellPanels>);rerender(<FileShellPanels panels={panels} active={null} onActiveChange={change} label="File side controls">Content</FileShellPanels>);expect(screen.getByRole('button',{name:'Version history'})).toHaveFocus();});
 it('clears unavailable owner panel state when review access is revoked',()=>{const change=vi.fn();const props={header:{title:'Proposal',fileTypeLabel:'HTML file',fileKind:'htmlFile' as const},participants:[],panels:[{purpose:'review' as const,label:'Review',content:<p>Review</p>}],activePanel:'review' as const,onPanelChange:change,annotationMode:null,onAnnotationModeChange:vi.fn(),commands:[]};const {rerender}=render(<FileShell {...props} capabilities={{read:true,write:true,comment:true,review:true}}>Content</FileShell>);rerender(<FileShell {...props} capabilities={{read:true,write:true,comment:true,review:false}}>Content</FileShell>);expect(change).toHaveBeenCalledWith(null);expect(screen.queryByRole('complementary')).toBeNull();});
 it('separates comment/review/write capability and hides protected content on denial',()=>{const {rerender}=render(<Shell write={false} comment review={false}/>);expect(screen.queryByRole('button',{name:/Rename file/})).toBeNull();expect(screen.getByRole('button',{name:'Drop pin'})).toBeEnabled();expect(screen.queryByRole('button',{name:'Review'})).toBeNull();rerender(<Shell read={false}/>);expect(screen.queryByText('Protected content')).toBeNull();expect(screen.queryByRole('group',{name:'File side controls'})).toBeNull();expect(screen.getByText('Access unavailable.')).toBeVisible();});
 it('uses semantic kind in preference to an arbitrary legacy icon',()=>{render(<FileHeader title="Proposal" fileTypeLabel="HTML file" fileKind="htmlFile" icon={<span>Wrong glyph</span>}/>);expect(screen.queryByText('Wrong glyph')).toBeNull();expect(screen.getByRole('img',{name:'HTML file'}).querySelector('.lucide-panel-top')).not.toBeNull();});
 it('renders unknown facts and omits inapplicable rows',()=>{render(<FileMetadata label="Facts" rows={[{label:'ID',value:null},{label:'Approval',value:'not applicable',applicable:false}]}/>);expect(screen.getByRole('rowheader',{name:'ID'})).toBeVisible();expect(screen.getByRole('cell',{name:'—'})).toBeVisible();expect(screen.queryByText('Approval')).toBeNull();});
 it('requires restore confirmation, suppresses repeats, and retains failure for retry',async()=>{let reject!:(reason?:unknown)=>void;const restore=vi.fn(()=>new Promise<void>((_,r)=>{reject=r;}));render(<FileVersionHistory versions={versions} revisions={[]} state="ready" canSave={false} canRestore onRestore={restore}/>);fireEvent.click(screen.getByRole('button',{name:'Restore Checkpoint'}));expect(restore).not.toHaveBeenCalled();fireEvent.click(screen.getByRole('button',{name:'Confirm restore'}));expect(restore).toHaveBeenCalledTimes(1);expect(screen.getByRole('button',{name:'Confirm restore'})).toBeDisabled();reject(Error('failed'));await waitFor(()=>expect(screen.getByRole('alert')).toHaveTextContent('failed'));expect(screen.getByRole('button',{name:'Confirm restore'})).toBeEnabled();});
 it('does not expose save/restore without permissions and represents denied, loading and error',()=>{const props={versions,revisions:[],canSave:false,canRestore:false};const {rerender}=render(<FileVersionHistory {...props} state="ready"/>);expect(screen.queryByRole('button')).toBeNull();rerender(<FileVersionHistory {...props} state="loading"/>);expect(screen.getByRole('status')).toHaveTextContent('Loading');rerender(<FileVersionHistory {...props} state="denied"/>);expect(screen.queryByText('Checkpoint')).toBeNull();rerender(<FileVersionHistory {...props} state="error" error="Could not load"/>);expect(screen.getByRole('alert')).toHaveTextContent('Could not load');});
 it('has no obvious accessibility violations',async()=>{const {container}=render(<Shell/>);fireEvent.click(screen.getByRole('button',{name:'Comments'}));await expectA11yClean(container);});
});
