import fileHeaderExampleSource from '../../../src/gallery/FileHeaderExample.tsx?raw';
import React from 'react';
import { fileShellIcons } from '../../../src/semantics/file-shell-icons';
import { TooltipProvider } from '../../../src/ui/tooltip';
const { document: FileText, saved: Check, moreActions: MoreHorizontal, comments: MessageSquare, review: ClipboardCheck, fileInfo: Info, workingStatus: KanbanSquare } = fileShellIcons;
import { FileHeader } from '../../../src/ui/file-header';
import { Button } from '../../../src/ui/button';
import './file-header-template.css';
import { FileHeaderExample, ParticipantsPreview, DocumentToolbarPreview, FileHeaderStateExample } from '../../../src/gallery/FileHeaderExample';
import { PageTitle, SectionHeading } from './shared';

const examples = [
 {type:'HTML file',title:'Project proposal'}, {type:'Document',title:'Product direction'},
 {type:'Spreadsheet',title:'Quarterly forecast'}, {type:'Presentation',title:'Team introduction'}, {type:'Image',title:'Workspace overview'},
];
const iconGroups = [
 {title:'File identity',purposes:['htmlFile','document','spreadsheet','presentation','image']},
 {title:'Annotation and panels',purposes:['selectElement','dropCommentPin','comments','workingStatus','review','fileInfo','versionHistory']},
 {title:'Editor commands',purposes:['paragraph','heading1','heading2','bold','italic','strikethrough','inlineCode','bulletList','numberedList','indent','outdent','quote','codeBlock','horizontalRule','link','table','undo','redo']},
 {title:'File actions',purposes:['newFile','rename','duplicate','move','moreActions','saveVersion','restoreVersion','remove','pinToSpace','publish','canonical','defer','archive']},
 {title:'Persistence feedback',purposes:['saved','saving','offline','saveError']},
] as const;

function Recipe({children}:{children:string}) {
 return <details className="file-template-code"><summary>Code for this example</summary><pre><code>{children}</code></pre></details>;
}

export function FileHeaderTemplate() {
 const [level,setLevel]=React.useState('Complete shell');
 const [title,setTitle]=React.useState('Product direction');
 const [toolbarNotice,setToolbarNotice]=React.useState('');
 return <div className="file-template">
  <PageTitle eyebrow="Templates" title="File shell" summary="Header, file controls, toolbar and inspector around a content placeholder. Explore the shared shell across file types using fictional local state."/>
  <aside className="file-template-boundary" aria-label="Template delivery boundary"><strong>Design-system template · local preview</strong><p>This page defines composition, semantics and interaction examples. It is not the functioning Avalandra file view. Content, services, permissions, persistence, comments, presence, review and version operations must be connected and tested by Avalandra.</p><a href="#file-shell-handoff">Avalandra handoff responsibilities ↓</a></aside>
  <p><a href="#/components/file-header">Component properties, states and code examples →</a></p>
  <div className="file-template-levels" role="group" aria-label="File header design levels">
   {['Tokens','Atoms','Assemblies','Complete shell'].map(item=><button key={item} type="button" aria-pressed={level===item} onClick={()=>setLevel(item)}>{item}</button>)}
  </div>
  {level==='Tokens' && <section>
   <SectionHeading id="foundations">Foundations</SectionHeading>
   <p>The header uses the same semantic tokens in every file type. Change the site theme to inspect both palettes.</p>
   <div className="file-template-grid">{[
    ['Surface','--weft-paper','color'],['Text','--weft-ink','color'],['Supporting text','--weft-muted','color'],['Boundary','--weft-rule','color'],['Focus and selection','--primary','color'],['Selection tint','color-mix: --primary 16% + --weft-paper','color'],['Application font','--weft-font-sans','font'],
   ].map(([name,token,family])=><a className="file-template-card" href={`#/tokens/${family}`} key={token}><strong>{name}</strong><code>{token}</code></a>)}</div>
   <p>Layout constants: 44px minimum control targets; 24px desktop / 20px narrow-screen titles; 12px breadcrumbs and save feedback; 56px desktop utility rail; 300px desktop inspector. These are composition values, not new token exports. Selection uses blue tint and outline, never a gray or solid primary fill. Controls have a 44px minimum target. Titles wrap; actions move onto another row when space is limited. Optional decorative file icons are omitted on narrow screens.</p>
  </section>}
  {level==='Atoms' && <section>
   <SectionHeading id="atoms">File-shell atoms</SectionHeading>
   <p>These are the pieces of the composition, not separate new package components.</p>
   <div className="file-template-grid">
    <article className="file-template-card"><h3>File identity</h3><div className="file-template-sample"><FileText aria-hidden="true" size={24}/><span>Document</span></div><p>The icon represents the file type without a separate visible caption. The icon tooltip exposes the type on hover and focus; accessible text preserves it for screen readers.</p><Recipe>{'fileTypeLabel="Document"\nicon={<fileShellIcons.document size={20} />}'}</Recipe></article>
    <article className="file-template-card"><h3>Title</h3><div className="file-template-sample"><strong>Product direction</strong></div><p>The file name is a heading. Choose its level to fit the host page; long names wrap.</p><Recipe>{'title="Product direction"\nheadingLevel={1}'}</Recipe></article>
    <article className="file-template-card"><h3>Click-to-edit title</h3><div className="file-template-sample"><button type="button" className="weft-file-header-title-edit" onClick={()=>setLevel('Assemblies')}>Product direction</button></div><p>Providing onRename makes the title a keyboard-accessible editing control. Try the full keyboard interaction in Assemblies.</p><Recipe>{'onRename={setTitle}'}</Recipe></article>
    <article className="file-template-card"><h3>Save feedback</h3><div className="file-template-sample"><Check size={16} aria-hidden="true"/><span>All changes saved</span></div><p>Icon plus text communicates persistence. Omit it when the application has no verified save state.</p><Recipe>{'saveState="saved"'}</Recipe></article>
    <article className="file-template-card"><h3>Location</h3><div className="file-template-sample">Studio / Research</div><p>The optional context slot orients the user. Supply real links when destinations exist.</p><Recipe>{'context={<span>Studio / Research</span>}'}</Recipe></article>
    <article className="file-template-card"><h3>Actions</h3><div className="file-template-sample"><Button variant="ghost" size="icon" aria-label="Explore file actions" onClick={()=>setLevel('Complete shell')}><MoreHorizontal aria-hidden="true" size={18}/></Button></div><p>The header action slot holds HTML annotation modes, presence and the file menu. Comments, working status, review and info belong in the side rail. Explore their composition in Assemblies.</p><Recipe>{'actions={<FileActions />}'}</Recipe></article>
   </div>
  </section>}
  {level==='Atoms' && <section><SectionHeading id="collaboration">Collaboration and file controls</SectionHeading><div className="file-template-grid">{[
   ['Comments',MessageSquare,'First in the side rail. Opens the comments panel; an optional total count is distinct from unread activity.'],
   ['Review',ClipboardCheck,'Available to writers when review is supported. Review confirmation is separate from save feedback.'],
   ['Document / file info',Info,'The far-right info icon opens file metadata. Version history has its own rail control and panel, separate from file metadata. Expose expanded state and return focus when closing.'],
   ['Working status',KanbanSquare,'In the far-right rail, the Kanban icon opens a working-status panel with Active, Stale, WIP or Clear. This describes the work, not whether changes have saved.'],
   ['More actions',MoreHorizontal,'Opens the file operations menu. The application supplies the permitted operations.'],
  ].map(([name,Icon,note])=>{const Glyph=Icon as typeof MessageSquare;return <article className="file-template-card" key={name as string}><h3>{name as string}</h3><div className="file-template-sample"><Glyph size={20} aria-hidden="true"/><span>{name as string}</span></div><p>{note as string}</p></article>})}<article className="file-template-card"><h3>Participant presence</h3><div className="file-template-sample">AC · JL</div><p>Represent current participants by name, including agent identity. Omit presence when no verified participants exist. The Document example stacks six fictional participants with a +3 overflow list. Avalandra’s SessionParticipant contract provides actor ID, name and human/agent kind; it does not provide active-editing, idle or last-seen state. Label presence as “In this file session” and keep editing activity unknown.</p></article></div><Recipe>{fileHeaderExampleSource}</Recipe></section>}
  {level==='Atoms' && <section><SectionHeading id="semantic-atoms">Semantic icon inventory</SectionHeading><p>All icons come from fileShellIcons. Version history is represented by its own panel and saved-version/revision-lineage assembly. The same image glyph means file type in identity and insert image in the editor; both refer to image content.</p>{iconGroups.map(group=><div key={group.title}><h3>{group.title}</h3><div className="file-template-icon-inventory">{group.purposes.map(purpose=>{const Glyph=fileShellIcons[purpose];return <div key={purpose}><Glyph size={20} aria-hidden="true"/><code>{purpose}</code></div>})}</div></div>)}<div className="file-template-grid"><article className="file-template-card"><h3>Count and selected state</h3><p>Comments may carry a total-count badge; unknown is uncounted, not zero. Open rail controls expose aria-expanded and use a blue tinted selection with an outline. A second click closes the panel.</p></article><article className="file-template-card"><h3>Metadata row and unknown value</h3><table className="file-preview-metadata"><caption className="weft-sr-only">Example metadata atoms</caption><tbody><tr><th scope="row">File ID</th><td>—</td></tr></tbody></table><p>Two aligned cells with a row header; em dash means no supplied value. Do not invent approval or revision data.</p></article><article className="file-template-card"><h3>Permission and error states</h3><p>Omit unavailable actions. Disabled actions explain unavailable capability. Rename errors retain the draft. Unknown save state renders no success claim.</p></article></div></section>}
  {level==='Assemblies'  && <section>
   <SectionHeading id="assemblies">Atoms working together</SectionHeading>
   <div className="file-template-grid">
    <article className="file-template-card"><h3>Identity and inline rename</h3><FileHeader title={title} fileTypeLabel="Document" headingLevel={3} onRename={setTitle}/><p>Clicking the title or activating it with Enter or Space opens an explicitly named input. Enter or leaving the title confirms; Escape restores the title. Enter and Escape return focus to the title; blur preserves focus on the next control.</p><Recipe>{'const [title, setTitle] = React.useState("Product direction");\n<FileHeader title={title} fileTypeLabel="Document" headingLevel={3} onRename={setTitle} />'}</Recipe></article>
    <article className="file-template-card"><h3>Read-only identity</h3><FileHeader title="Quarterly forecast" fileTypeLabel="Spreadsheet" headingLevel={3}/><p>Omit onRename when editing is unavailable. Keep the title readable without displaying an inactive editing control.</p><Recipe>{'<FileHeader title="Quarterly forecast" fileTypeLabel="Spreadsheet" headingLevel={3} />'}</Recipe></article>
   </div>
   <SectionHeading id="save-states">Persistence feedback</SectionHeading>
   <div className="file-template-grid">{(['saved','saving','offline','error'] as const).map(state=><article className="file-template-card" key={state}><FileHeader title="Product direction" fileTypeLabel="Document" headingLevel={3} saveState={state}/><Recipe>{`<FileHeader title="Product direction" fileTypeLabel="Document" headingLevel={3} saveState="${state}" />`}</Recipe></article>)}</div>
   <p>Save feedback is separate from workflow labels such as “In review”. Applications own persistence, permissions and recovery actions.</p>
   <article className="file-template-card"><h3>Rename failure and retry</h3><FileHeaderStateExample title="Product direction" fileTypeLabel="Document" headingLevel={3} failRename/><p>This fixture deliberately rejects rename. The draft and error remain available; Escape cancels. This is not a service failure from Avalandra.</p></article>
   <SectionHeading id="presence-assembly">Presence roster and overflow</SectionHeading><p>The same roster used in the full shell: two participants, then six with stacking and overflow. Names and agent identities remain available; editing activity is unknown.</p><div className="file-template-grid">{[false,true].map(crowded=><article className="file-template-card" key={String(crowded)}><TooltipProvider><ParticipantsPreview crowded={crowded}/></TooltipProvider><p>{crowded?'Six fictional participants; three visible and +3 overflow.':'Two fictional session participants.'}</p></article>)}</div>
   <SectionHeading id="toolbar-assembly">Document formatting toolbar</SectionHeading><p>Commands wrap only within the document column. These buttons announce intent; the host editor must supply selection, enabled states and execution.</p><DocumentToolbarPreview onCommand={label=>setToolbarNotice(`${label}: preview only; no editor connected.`)}/><p role="status">{toolbarNotice}</p>
   <SectionHeading id="workspace-assembly">Content column, rail and one panel</SectionHeading><p>This assembly reuses the complete shell’s workspace without the header. Switch panels with the rail; activate an open icon again to close it. The panel is a persistent region, not a dismissible layer. Escape is reserved for the content editor and for transient controls inside the panel. The rail control toggles the panel; closing it keeps focus on that control. Shift+Tab from the panel returns to the rail. No duplicate tabs or close button. Metadata uses rows; status uses radios; review requires an explicit confirmation.</p><FileHeaderExample workspaceOnly title="Product direction" fileTypeLabel="Document" initialPane="comments" commentCount={3} previewContent={<p>Content area placeholder</p>}/>
   <SectionHeading id="states-assembly">Loaded data and access states</SectionHeading><p>These fixtures exercise the same exported composition. Version history and Review menu entries open their corresponding rail panels. Unknown activity is not inferred from presence.</p>{(['ready','loading','error','denied','read-only','comment-only'] as const).map(scenario=><details key={scenario}><summary>{scenario}</summary><FileHeaderExample key={scenario} title="Project proposal" fileTypeLabel="HTML file" populated commentCount={3} initialPane="details" viewState={scenario==='read-only'||scenario==='comment-only'?'ready':scenario} capabilities={{read:true,write:scenario!=='read-only'&&scenario!=='comment-only',comment:scenario!=='read-only',review:scenario!=='read-only'&&scenario!=='comment-only'}} previewContent={<p>Fictional content placeholder</p>}/></details>)}
   <SectionHeading id="html-assembly">HTML annotation controls and cursor</SectionHeading><p>HTML has no rich-text toolbar. Its mutually exclusive modes use matching cursors only over the content surface. This example changes mode and cursor, but does not target elements or create annotations.</p><FileHeaderExample title="Project proposal" fileTypeLabel="HTML file" previewContent={<div className="file-preview-placeholder">Move the pointer here to inspect the active annotation cursor.</div>}/>

  </section>}
  <details style={{marginTop:24}}><summary>Source comparison and boundaries</summary><p>Evidence: Avalandra checkout 7cd12967 plus the live screenshots supplied during review. The local checkout omitted deployed rail controls, so it is incomplete evidence. This template expresses the agreed Weft composition, not deployed-source parity. HTML annotation modes and matching cursors are represented; actual targeting and pin persistence are host responsibilities. Version history now has a controlled panel and callback-driven save/restore states; service execution remains Avalandra-owned.</p></details>
  {level==='Complete shell' && <><SectionHeading id="complete">Complete file workspace shell</SectionHeading><p>The complete shell around a content placeholder for each file type. The Document example shows a count of 3 on the comments rail; the other examples show the uncounted treatment. Counts represent application-supplied comments, not unread activity. Rename and working status are local. Every implemented far-right rail icon opens a view in the same side panel: Comments, Status, Review, File info or Version history. The Review panel contains the explicit Mark reviewed action; menu actions announce local feedback.</p>{examples.map(example=><section key={example.type} style={{marginTop:32}}>
   <SectionHeading id={`file-${example.type.toLowerCase()}`}>{example.type}</SectionHeading>
   <div style={{border:'1px solid var(--weft-rule)',background:'var(--weft-paper)',minWidth:0}}>
    <FileHeaderExample title={example.title} fileTypeLabel={example.type} saveState="saved" commentCount={example.type==='Document'?3:undefined} initialPane="comments" previewContent={<div className="file-preview-placeholder"><strong>{example.type} content</strong><p>The file’s contents are outside this template’s scope.</p></div>}/>
   </div>
   <details style={{marginTop:12}}><summary>Code for this header</summary><pre style={{overflowX:'auto',padding:16,border:'1px solid var(--weft-rule)',fontSize:12}}><code>{`const [title, setTitle] = React.useState(${JSON.stringify(example.title)});\n\n<FileHeader\n  title={title}\n  fileTypeLabel="${example.type}"\n  context={<span>Studio / Research</span>}\n  saveState="saved"\n  onRename={setTitle}\n  icon={<${example.type==='HTML file'?'fileShellIcons.htmlFile':example.type==='Document'?'fileShellIcons.document':example.type==='Spreadsheet'?'fileShellIcons.spreadsheet':example.type==='Presentation'?'fileShellIcons.presentation':'fileShellIcons.image'} size={20} />}\n  actions={<FileActions />}\n/>\n\n// FileActions uses NavigationActions and the shared semantic icon mapping.
// This recipe shows only FileHeader; it does not instantiate the full workspace.\n// Complete shell preview implementation follows below.`}</code></pre></details>
  </section>)}<Recipe>{fileHeaderExampleSource}</Recipe></>}
 <section id="file-shell-handoff"><SectionHeading id="handoff">Avalandra integration handoff</SectionHeading><p><a href="https://nodaste.hub.avalandra.com/d/9cd07649-bea9-4e30-ae60-5b6246cae395">Read the Avalandra handoff document →</a></p><p><strong>Template, not a production deliverable.</strong> FileHeader and file-shell-controls are package primitives. FileShell is the registered React composition. FileHeaderExample, ParticipantsPreview and DocumentToolbarPreview are gallery demonstrations with fictional local state. They are reference compositions, not service adapters or editor implementations.</p><table className="file-preview-metadata"><caption>Ownership at handoff</caption><thead><tr><th>Weft reference</th><th>Avalandra must implement</th></tr></thead><tbody>{[
 ['Identity and rename','Bind real file identity, permissions, validation, collisions and asynchronous persistence; resolve rename only after successful save.'],
 ['Save feedback','Derive saved/saving/offline/error from actual persistence; never use the fixture saved state as production truth.'],
 ['HTML modes and cursor','Connect element hit testing, coordinate transforms, zoom/scroll, sandbox iframe cursor propagation, annotation anchors and persisted threads.'],
 ['Formatting toolbar','Connect editor commands, selection/context, disabled and pressed states, undo/redo and table-specific actions.'],
 ['Comments and presence','Fetch actual totals/threads and verified session participants. Do not infer unread counts or active editing from membership.'],
 ['Status, review and file actions','Enforce capabilities; persist changes; provide confirmations, dialogs, failures and recovery. Review is separate from approval.'],
 ['Metadata and version history','Supply real metadata and revisions. Connect the version-history panel and its loading/empty/error states, saved versions versus revision lineage, save labels, restore confirmation and callback failures. Preview operations modify local fixtures only.'],
 ['Accessibility and responsive behavior','Validate keyboard/focus, screen readers, touch, themes, zoom, reduced motion and iframe boundaries in the real file view.'],
 ].map(([reference,host])=><tr key={reference}><th scope="row">{reference}</th><td>{host}</td></tr>)}</tbody></table><p>Release status: this is uncommitted design-system work. Site builds and scoped tests demonstrate preview behavior; they are not Avalandra acceptance testing. Package adoption, service integration and end-to-end verification remain separate work.</p></section>
 </div>;
}
