import React from 'react';
import './html-layout-guidance.css';

const sources={work:'work-status',case:'callout-contrast',proposal:'card-columns',code:'code-overflow'};
function DontExample({title}:{title:string}){
 if(title==='Pair callout colors')return <div className="html-layout-bad-demo"><div className="html-layout-yellow-swatch" aria-hidden="true"/><p><strong>Local failure fixture:</strong> near-white text inherited from a dark page on a bright yellow surface.</p><pre><code>{'background: var(--highlight);\n/* no paired foreground */'}</code></pre></div>;
 if(title==='Give state a readable name')return <div className="html-layout-bad-demo"><div className="html-layout-color-only" aria-hidden="true"><span/><span/><span/></div><p>Three colored marks, with no state names or explanation.</p></div>;
 if(title==='Let card columns reflow')return <div className="html-layout-bad-demo"><div className="html-layout-fixed-cards" aria-hidden="true">{['Shared context','Focused workstreams','Clear handoffs'].map(t=><div key={t}><strong>{t}</strong><p>Content stays in three cramped columns even inside a narrow document.</p></div>)}</div><p>Fixed three-column grid; text is clipped to force matching heights.</p></div>;
 if(title==='Make summary metrics useful')return <div className="html-layout-bad-demo"><div className="html-layout-unlabeled-metrics"><strong>0</strong><strong>3</strong></div><p>Values without labels or a meaningful destination.</p></div>;
 if(title==='Expand supporting detail inline')return <div className="html-layout-bad-demo"><details><summary>More</summary><p>The next action is hidden here: review the proposal.</p></details><p>A vague summary hides the information readers need to act.</p></div>;
 if(title==='Label visual comparisons')return <div className="html-layout-bad-demo"><div className="html-layout-image-pair" aria-hidden="true"><div>Image A</div><div>Image B</div></div><p>No version, viewport or explanation of the difference.</p></div>;
 if(title==='Keep wide tables readable')return <div className="html-layout-bad-demo"><p>Item / Owner / Measurement / Evidence / Next action</p><p>Columns squeezed together; no clear association between headers and values.</p></div>;
 if(title==='Explain workflow branches')return <div className="html-layout-bad-demo"><p aria-hidden="true">Review → ◇ → Publish / Revise</p><p>The branch has no question or named outcomes.</p></div>;
 if(title==='Make changes explicit')return <div className="html-layout-bad-demo"><div className="html-layout-color-only" aria-hidden="true"><span/><span/></div><p>Color distinguishes two versions, but nothing says which text was added or removed.</p></div>;
 if(title==='Help readers navigate long documents')return <div className="html-layout-bad-demo"><p>Section 1 · Section 2 · Section 3</p><p>Generic labels without working links make readers search by scrolling.</p></div>;
 return <div className="html-layout-bad-demo"><div className="html-layout-clipped-code" aria-hidden="true">document: title: Review notes status: draft evidence: Record the source and limitations before drawing a conclusion.</div><p>Whitespace flattened and the long line clipped.</p></div>;
}
function Pair({title,source,dont,doText,children}:{title:string;source:string;dont:string;doText:string;children:React.ReactNode}){return <section className="html-layout-example"><h2>{title}</h2><span className="html-layout-note">Local reference pair · {source}</span><div className="html-layout-pair"><section><h3>Don’t</h3><p>{dont}</p><DontExample title={title}/></section><section><h3>Do</h3><p>{doText}</p>{children}</section></div></section>;}
export function HtmlLayoutGuidance(){return <div className="weft-doc html-layout-guide"><h2>Layout choices that help readers</h2><p>These self-contained examples preserve the issues we reviewed and their alternatives. They illustrate useful choices, not required layouts. Failure demonstrations are contained and labeled; inaccessible text is represented with a readable explanation.</p>
<Pair title="Pair callout colors" source={sources.case} dont="Set a bright highlight background and let it inherit the page’s text color. A dark page can then produce near-white text on yellow." doText="Choose foreground and surface together for each theme. Use a visible lead-in and a border when emphasis is useful."><aside className="html-layout-callout"><strong>Important:</strong> A partial result does not establish that no other results exist.</aside><p className="html-layout-note">This example uses the readable page foreground on a subtle surface, with an accent border. Strong fills are also possible when their text pairing passes contrast checks. Follow the reader’s selected Ava theme through its supplied theme variables; OS dark-mode rules alone can disagree with that selection.</p></Pair>
<Pair title="Give state a readable name" source={sources.work} dont="Make a colored stripe or fill carry the entire meaning, or use the same yellow highlight for unrelated states." doText="Use explicit state text, with semantic color as a supporting cue. Reuse an existing Weft state treatment when it fits."><div className="html-layout-state-row"><span>✓ Complete</span><span>! Needs review</span><span>— Not started</span></div><p className="html-layout-note">State names and symbols remain clear with color removed. These are authored examples, not live workflow controls.</p></Pair>
<Pair title="Let card columns reflow" source={sources.proposal} dont="Force three narrow columns at every width, or truncate body text to make cards match." doText="Use a responsive grid, align cards within each row, and let content determine height. Preserve reading order when cards stack."><div className="html-layout-cards">{[['1','Shared context','Give readers the goal, owner and supporting evidence.'],['2','Focused workstreams','Separate distinct work while keeping a shared structure for decisions, feedback and status.'],['3','Clear handoffs','Explain what happens next and who needs to respond.']].map(([n,title,body])=><section key={n}><span className="html-layout-marker">{n}</span><h4>{title}</h4><p>{body}</p></section>)}</div></Pair>
<Pair title="Make summary metrics useful" source={sources.work} dont="Show an unexplained number, hide zero values, or style a card as a link without a destination." doText="Pair each value with a label. Use an anchor when it leads to the relevant section; keep zero explicit. Include units and measurement context, and distinguish an unknown value from zero."><div className="html-layout-metrics"><a href="#layout-questions"><strong>0</strong><span>Questions awaiting an answer ↓</span></a><div><strong>3</strong><span>Examples reviewed</span></div><div><strong>Not measured</strong><span>Load time (ms)</span></div></div><p className="html-layout-note">Illustrative counts as of 7 October 2026. Load time has not been tested; no sample or timing claim is implied.</p><section id="layout-questions"><h4>Questions awaiting an answer</h4><p>No questions are waiting in this illustrative example.</p></section></Pair>
<Pair title="Expand supporting detail inline" source={sources.work} dont="Hide the decision or next action inside an unnamed collapsed panel." doText="Keep the essential message visible. Give optional context a descriptive summary and let it expand in place."><p><strong>Next step:</strong> Review the proposal.</p><details className="html-layout-panel"><summary>Supporting evidence and assumptions</summary><p>Explain the evidence, its limits and any assumptions here. Native disclosure supports keyboard and touch without a custom script.</p></details></Pair>
<Pair title="Keep code overflow local" source={sources.code} dont="Flatten multiline text, clip a long command, or let code widen the whole document." doText="Preserve whitespace and scroll the code area independently. Include short commands and multiline text when useful."><pre role="region" tabIndex={0} aria-label="Example command"><code>npm run build</code></pre><pre role="region" tabIndex={0} aria-label="Example multiline configuration"><code>{'document:\n  title: Review notes\n  status: draft\n  evidence: Record the source and limitations before drawing a conclusion.'}</code></pre></Pair>
<Pair title="Label visual comparisons" source="image-comparison" dont="Place two screenshots together without identifying versions, conditions or what changed." doText="Label each view and use comparable conditions. Explain the difference, provide image alternatives and offer a full-size view for real captures."><div className="html-layout-image-pair"><figure><div className="html-layout-wireframe" role="img" aria-label="Before: a form with an unlabeled input"><span>Before</span><div>Input</div></div><figcaption>Previous version · desktop, 1280 × 800 · light theme</figcaption></figure><figure><div className="html-layout-wireframe" role="img" aria-label="After: the input has a visible Project name label"><span>After</span><span>Project name</span><div>Input</div></div><figcaption>Revised version · same viewport and theme</figcaption></figure></div><p className="html-layout-note">Local schematic comparison: the revised form adds a visible label. For screenshots, link the full-size capture; label missing captures explicitly.</p></Pair>
<Pair title="Keep wide tables readable" source="wide-table" dont="Shrink text to fit every column or let a table widen the entire page." doText="Use a caption, associated headers and clear units. When necessary, keep horizontal scrolling inside a named, keyboard-focusable region."><p id="layout-table-title"><strong>Response time comparison · illustrative data</strong></p><div className="html-layout-table-scroll" role="region" aria-labelledby="layout-table-title" tabIndex={0}><table><caption className="html-layout-sr-only">Response time comparison · illustrative data</caption><thead><tr><th scope="col">Scenario</th><th scope="col">Median (ms)</th><th scope="col">Samples</th><th scope="col">Measurement context</th></tr></thead><tbody><tr><th scope="row">Initial load</th><td>240</td><td>20</td><td>Desktop · controlled local fixture</td></tr><tr><th scope="row">Reconnect</th><td>Not measured</td><td>—</td><td>No measurement available</td></tr></tbody></table></div><p className="html-layout-note">Scroll this table horizontally on narrow screens. Keep essential comparisons close together.</p></Pair>
<Pair title="Explain workflow branches" source="workflow" dont="Rely on arrows, spatial arrangement or unlabeled diamonds to explain a process." doText="Use ordered steps and explicit branch outcomes. Keep a clear linear reading order as the layout reflows. Use flowcharts, connected cards or ordered steps by default; use ASCII diagrams only when explicitly requested."><ol className="html-layout-flow"><li><strong>Review the draft.</strong><p>Check evidence and unresolved questions.</p></li><li><strong>Is it ready?</strong><p>Yes: publish the approved draft. No: revise it and return to review.</p></li><li><strong>Record the outcome.</strong><p>Keep the decision and its rationale together.</p></li></ol></Pair>
<Pair title="Make changes explicit" source="change-comparison" dont="Use color alone to show additions and removals, or omit which versions are compared." doText="Name the versions and label changes in text. Preserve context, and use native insertion/deletion semantics when helpful."><p><strong>Draft 1 → Draft 2</strong> · illustrative wording change</p><div className="html-layout-change"><p><strong>Removed:</strong> <del>Send feedback soon.</del></p><p><strong>Added:</strong> <ins>Send feedback by Friday.</ins></p><p><strong>Unchanged context:</strong> Reply in the document’s comment thread.</p></div></Pair>
<Pair title="Help readers navigate long documents" source="document-navigation" dont="Use generic section names or make readers scroll through an entire document to find a topic." doText="Provide descriptive section links and stable heading IDs. Keep navigation usable when wrapped or zoomed, and leave linked headings visible."><nav aria-label="Local example sections" className="html-layout-section-links"><a href="#layout-example-goal">Goal</a><a href="#layout-example-evidence">Evidence</a><a href="#layout-example-decision">Decision</a></nav><section id="layout-example-goal"><h4>Goal</h4><p>Make the document easy to scan.</p></section><section id="layout-example-evidence"><h4>Evidence</h4><p>Keep supporting material near the claim it supports.</p></section><section id="layout-example-decision"><h4>Decision</h4><p>State the next action clearly.</p></section></Pair>
</div>;}
