import * as React from 'react';
import { Button } from './button';
import { Input } from './input';
import { Popover, PopoverTrigger, PopoverContent } from './popover';
import { Tooltip, TooltipTrigger, TooltipContent, TooltipProvider } from './tooltip';
import { fileShellIcons, type FileShellIconPurpose } from '../semantics/file-shell-icons';

export type FilePanelPurpose = 'comments' | 'workingStatus' | 'review' | 'fileInfo' | 'versionHistory';
export type FileShellPanel = { purpose: FilePanelPurpose; label: string; content: React.ReactNode; count?: number };
export type FileShellPanelsProps = { panels: readonly FileShellPanel[]; active: FilePanelPurpose | null; onActiveChange: (purpose: FilePanelPurpose | null) => void; children: React.ReactNode; label: string };
/** Exclusive controlled panels. Chrome owns focus; the application owns content and capabilities. */
export function FileShellPanels({panels,active,onActiveChange,children,label}:FileShellPanelsProps) {
 const id=React.useId();const panel=panels.find(p=>p.purpose===active);const region=React.useRef<HTMLElement>(null);const triggers=React.useRef(new Map<string,HTMLButtonElement>());const previous=React.useRef(active);
 const keyboard=React.useRef(true);
 React.useEffect(()=>{const pointer=()=>{keyboard.current=false;};const key=()=>{keyboard.current=true;};document.addEventListener('pointerdown',pointer,true);document.addEventListener('keydown',key,true);return()=>{document.removeEventListener('pointerdown',pointer,true);document.removeEventListener('keydown',key,true);};},[]);
 React.useEffect(()=>{let frame:number|undefined;if(panel&&previous.current!==active&&keyboard.current){region.current?.focus({preventScroll:true});frame=requestAnimationFrame(()=>region.current?.focus({preventScroll:true}));}else if(!panel&&previous.current&&keyboard.current){triggers.current.get(previous.current)?.focus({preventScroll:true});}previous.current=active;return()=>{if(frame!==undefined)cancelAnimationFrame(frame);};},[active,!!panel]);
 return <div className="weft-file-shell-workspace">
 <div role="group" aria-label={label} className="weft-file-shell-rail"><TooltipProvider>{panels.map(item=>{const Glyph=fileShellIcons[item.purpose];return <Tooltip key={item.purpose}><TooltipTrigger asChild><Button ref={node=>{if(node)triggers.current.set(item.purpose,node);else triggers.current.delete(item.purpose);}} type="button" variant="ghost" size="icon" aria-label={item.count===undefined?item.label:`${item.label}, ${item.count} total`} aria-expanded={active===item.purpose} aria-controls={active===item.purpose&&panel?id:undefined} onClick={()=>{onActiveChange(active===item.purpose?null:item.purpose);}}><Glyph size={19} aria-hidden="true"/>{item.count!==undefined&&<span className="weft-file-shell-count" aria-hidden="true">{item.count>99?'99+':item.count}</span>}</Button></TooltipTrigger><TooltipContent>{item.label}</TooltipContent></Tooltip>})}</TooltipProvider></div><div className="weft-file-shell-content">{children}</div> {panel&&<aside id={id} ref={region} tabIndex={-1} onKeyDown={event=>{if(event.key!=='Tab'||!event.shiftKey||event.defaultPrevented)return;const first=region.current?.querySelector<HTMLElement>('button:not(:disabled), input:not(:disabled), select:not(:disabled), textarea:not(:disabled), a[href], [tabindex="0"], [contenteditable="true"]');if(event.target===region.current||event.target===first){event.preventDefault();triggers.current.get(active!)?.focus({preventScroll:true});}}} aria-label={panel.label} className="weft-file-shell-panel"><div className="weft-file-shell-panel-heading"><strong>{panel.label}</strong></div><div className="weft-file-shell-panel-body">{panel.content}</div></aside>}
</div>;
}
export type FileParticipant = { id: string; name: string; initials: string; kind: 'human'|'agent'; activity?: 'editing'|'idle' };
export type FilePresenceProps = { participants: readonly FileParticipant[]; label: string };
export function FilePresence({participants,label}:FilePresenceProps){
 if(!participants.length)return null;const stacked=participants.length>=5;
 const description=(p:FileParticipant)=>`${p.name}${p.kind==='agent'?' · Agent':''} · In this file session · ${p.activity==='editing'?'Editing now':p.activity==='idle'?'Idle':'Editing activity unknown'}`;
 return <div className="weft-file-presence"><TooltipProvider><ul aria-label={label} data-stacked={stacked}>{participants.slice(0,stacked?3:4).map(p=><li key={p.id}><Tooltip><TooltipTrigger asChild><span role="img" tabIndex={0} className="weft-file-person" aria-label={description(p)} data-activity={p.activity}><span className="weft-file-person-visual" aria-hidden="true">{p.initials}</span></span></TooltipTrigger><TooltipContent className="weft-file-person-tooltip">{description(p)}</TooltipContent></Tooltip></li>)}</ul></TooltipProvider>{stacked&&<Popover><PopoverTrigger asChild><Button type="button" variant="ghost" aria-label={`+${participants.length-3}, show all ${participants.length} participants`}>+{participants.length-3}</Button></PopoverTrigger><PopoverContent className="weft-file-presence-list"><ul>{participants.map(p=><li key={p.id}>{description(p)}</li>)}</ul></PopoverContent></Popover>}</div>;
}
export type FileAnnotationMode = 'selectElement'|'dropCommentPin';
export type FileAnnotationModesProps = { mode: FileAnnotationMode | null; onModeChange: (mode: FileAnnotationMode) => void; disabled?: boolean };
export function FileAnnotationModes({mode,onModeChange,disabled}:FileAnnotationModesProps){return <div role="group" aria-label="HTML annotation mode" className="weft-file-annotation-modes"><TooltipProvider>{(['selectElement','dropCommentPin'] as const).map(purpose=>{const Glyph=fileShellIcons[purpose];const label=purpose==='selectElement'?'Select element':'Drop pin';return <Tooltip key={purpose}><TooltipTrigger asChild><Button type="button" variant="ghost" size="icon" disabled={disabled} aria-label={label} aria-pressed={mode===purpose} data-annotation-icon={purpose} onClick={()=>onModeChange(purpose)}><Glyph size={18} aria-hidden="true"/></Button></TooltipTrigger><TooltipContent>{label}</TooltipContent></Tooltip>})}</TooltipProvider></div>;}
/** Host iframes must carry the cursor into their own document; this hook owns only the supplied surface. */
export function useFileAnnotationCursor(surface:React.RefObject<HTMLElement|null>,scope:React.RefObject<HTMLElement|null>,mode:FileAnnotationMode|null){React.useEffect(()=>{
 const element=surface.current;if(!element||!mode)return;
 const update=()=>{const icon=scope.current?.querySelector<SVGSVGElement>(`[data-annotation-icon="${mode}"] svg`);if(!icon)return;const svg=icon.cloneNode(true) as SVGSVGElement;svg.setAttribute('xmlns','http://www.w3.org/2000/svg');svg.setAttribute('width','24');svg.setAttribute('height','24');svg.setAttribute('stroke',getComputedStyle(element).color);element.style.cursor=`url("data:image/svg+xml,${encodeURIComponent(svg.outerHTML)}") ${mode==='dropCommentPin'?'12 12':'8 8'}, ${mode==='dropCommentPin'?'crosshair':'default'}`;};update();const observer=new MutationObserver(update);observer.observe(document.documentElement,{attributes:true});observer.observe(document.body,{attributes:true});return()=>{observer.disconnect();element.style.removeProperty('cursor');};
 },[mode,surface,scope]);}
export type FileToolbarPurpose = 'paragraph'|'heading1'|'heading2'|'bold'|'italic'|'strikethrough'|'inlineCode'|'bulletList'|'numberedList'|'indent'|'outdent'|'quote'|'codeBlock'|'horizontalRule'|'link'|'table'|'image'|'undo'|'redo'|'comments';
export type FileToolbarCommand = { id: string; label: string; purpose: FileToolbarPurpose; disabled?: boolean; pressed?: boolean; onSelect: () => void };
export type FileToolbarProps = { commands: readonly FileToolbarCommand[]; label: string };
export function FileToolbar({commands,label}:FileToolbarProps){return <div className="weft-file-toolbar" role="group" aria-label={label}>{commands.map(c=>{const Glyph=fileShellIcons[c.purpose];return <Button key={c.id} type="button" variant="ghost" size="icon" aria-label={c.label} title={c.label} disabled={c.disabled} aria-pressed={c.pressed} onClick={c.onSelect}><Glyph size={18} aria-hidden="true"/></Button>})}</div>;}
export type FileMetadataRow = { label: string; value: React.ReactNode; applicable?: boolean };
export function FileMetadata({rows,label}:{rows:readonly FileMetadataRow[];label:string}){return <table className="weft-file-metadata"><caption className="weft-sr-only">{label}</caption><tbody>{rows.filter(r=>r.applicable!==false).map(r=><tr key={r.label}><th scope="row">{r.label}</th><td>{r.value??'—'}</td></tr>)}</tbody></table>;}
export type FileViewState = 'ready'|'loading'|'error'|'denied';
export function FileViewFeedback({state,error,onRetry,children}:{state:FileViewState;error?:string;onRetry?:()=>void;children:React.ReactNode}){return state==='loading'?<p role="status">Loading…</p>:state==='denied'?<p>Access unavailable.</p>:state==='error'?<div><p role="alert">{error??'Could not load this view.'}</p>{onRetry&&<Button type="button" onClick={onRetry}>Try again</Button>}</div>:<>{children}</>;}
export type FileSavedVersion = { id:string; label:string|null; revisionId:string; createdAt:string|null; creator:string|null; current?:boolean; canonical?:boolean };
export type FileRevision = { id:string; previousId:string|null; createdAt:string|null; creator:string|null; current?:boolean; canonical?:boolean };
export type FileVersionHistoryProps = { versions:readonly FileSavedVersion[]; revisions:readonly FileRevision[]; state:FileViewState; error?:string; canSave:boolean; canRestore:boolean; onRetry?:()=>void; onSave?:(label:string)=>Promise<void>; onRestore?:(version:FileSavedVersion)=>Promise<void> };
export function FileVersionHistory({versions,revisions,state,error,canSave,canRestore,onRetry,onSave,onRestore}:FileVersionHistoryProps){
 const [label,setLabel]=React.useState('');const [pending,setPending]=React.useState(false);const busy=React.useRef(false);const [failure,setFailure]=React.useState('');const [candidate,setCandidate]=React.useState<FileSavedVersion|null>(null);
 React.useEffect(()=>{setCandidate(null);},[versions,state,canRestore,onRestore]);
 const validCandidate=candidate&&versions.includes(candidate)&&state==='ready'&&canRestore?candidate:null;
 const run=async(work:()=>Promise<void>)=>{if(busy.current)return;busy.current=true;setPending(true);setFailure('');try{await work();setCandidate(null);setLabel('');}catch{setFailure('The version operation failed. Try again.');}finally{busy.current=false;setPending(false);}};
 return <FileViewFeedback state={state} error={error} onRetry={onRetry}><div aria-busy={pending}>{canSave&&onSave&&<form onSubmit={e=>{e.preventDefault();if(canSave)void run(()=>onSave(label.trim()));}}><label>Version label (optional)<Input value={label} readOnly={pending} onChange={e=>setLabel(e.target.value)}/></label><Button type="submit" disabled={pending}>Save version</Button></form>}<h3>Saved versions</h3>{versions.length?<ul className="weft-file-version-list">{versions.map(v=><li key={v.id}><strong>{v.label??'Unlabelled version'}</strong><p>{v.revisionId}{v.current?' · Current':''}{v.canonical?' · Canonical':''}</p><p>{v.createdAt??'—'} · {v.creator??'—'}</p>{canRestore&&onRestore&&<Button type="button" variant="ghost" disabled={pending} onClick={()=>setCandidate(v)}>Restore {v.label??v.revisionId}</Button>}</li>)}</ul>:<p>No saved versions yet.</p>}{validCandidate&&onRestore&&<div role="group" aria-label="Confirm version restore"><p>Restore {candidate.label??candidate.revisionId}? This creates a new current revision and keeps history.</p><Button type="button" disabled={pending} onClick={()=>void run(()=>onRestore(validCandidate))}>Confirm restore</Button><Button type="button" variant="ghost" disabled={pending} onClick={()=>setCandidate(null)}>Cancel restore</Button></div>}<h3>Revision lineage</h3>{revisions.length?<ol>{revisions.map(r=><li key={r.id}>{r.id}{r.current?' · Current':''}{r.canonical?' · Canonical':''}<p>Previous: {r.previousId??'—'} · {r.createdAt??'—'} · {r.creator??'—'}</p></li>)}</ol>:<p>No revision lineage supplied.</p>}{pending&&<p role="status">Saving version change…</p>}{failure&&<p role="alert">{failure}</p>}</div></FileViewFeedback>;
}
