// @vitest-environment jsdom
import * as React from 'react';
import {render,screen,fireEvent,waitFor,act} from '@testing-library/react';
import {it,expect,vi} from 'vitest';
import {FileHeader} from '../file-header';
import {axe} from 'jest-axe';
it('has a heading and type without inventing persistence or edit capabilities',()=>{render(<FileHeader title="Photo.png" fileTypeLabel="Image" headingLevel={2}/>);expect(screen.getByRole('heading',{level:2})).toHaveTextContent('Photo.png');expect(screen.queryByRole('button')).toBeNull();expect(screen.getByRole('status')).toBeEmptyDOMElement();});
it('saves a trimmed name once and restores rename focus',async()=>{const save=vi.fn();function Demo(){const [title,setTitle]=React.useState('Draft');return <FileHeader title={title} fileTypeLabel="Document" onRename={next=>{save(next);setTitle(next);}}/>;}render(<Demo/>);fireEvent.click(screen.getByRole('button',{name:/Rename file/}));const input=screen.getByRole('textbox',{name:'File name'});expect(input).toHaveFocus();fireEvent.change(input,{target:{value:'  New name  '}});fireEvent.keyDown(input,{key:'Enter'});await waitFor(()=>expect(screen.getByRole('heading')).toHaveTextContent('New name'));expect(save).toHaveBeenCalledExactlyOnceWith('New name');expect(screen.getByRole('button',{name:/Rename file/})).toHaveFocus();});
it('cancels with Escape without saving',()=>{const save=vi.fn();render(<FileHeader title="Draft" fileTypeLabel="Document" onRename={save}/>);fireEvent.click(screen.getByRole('button',{name:/Rename file/}));const input=screen.getByRole('textbox');fireEvent.change(input,{target:{value:'Unsaved'}});fireEvent.keyDown(input,{key:'Escape'});expect(screen.getByRole('heading')).toHaveTextContent('Draft');expect(screen.getByRole('button',{name:/Rename file/})).toHaveFocus();});
it('keeps an invalid or failed draft editable with an associated error',async()=>{const save=vi.fn().mockRejectedValue(new Error('offline'));render(<FileHeader title="Draft" fileTypeLabel="Document" onRename={save}/>);fireEvent.click(screen.getByRole('button',{name:/Rename file/}));const input=screen.getByRole('textbox');fireEvent.change(input,{target:{value:' '}});fireEvent.keyDown(screen.getByRole('textbox'),{key:'Enter'});expect(screen.getByRole('alert')).toHaveTextContent('Enter a file name');expect(save).not.toHaveBeenCalled();fireEvent.change(input,{target:{value:'New name'}});fireEvent.keyDown(screen.getByRole('textbox'),{key:'Enter'});await waitFor(()=>expect(screen.getByRole('alert')).toHaveTextContent('could not be renamed'));expect(input).toHaveValue('New name');expect(input).toHaveFocus();expect(input.getAttribute('aria-describedby')).toContain(screen.getByRole('alert').id);});
it('guards repeat submissions and composition while pending',async()=>{let finish:()=>void;const save=vi.fn(()=>new Promise<void>(resolve=>{finish=resolve;}));render(<FileHeader title="Draft" fileTypeLabel="Document" onRename={save}/>);fireEvent.click(screen.getByRole('button',{name:/Rename file/}));const input=screen.getByRole('textbox');fireEvent.change(input,{target:{value:'New name'}});fireEvent.keyDown(input,{key:'Enter',isComposing:true});expect(save).not.toHaveBeenCalled();fireEvent.keyDown(input,{key:'Enter'});fireEvent.keyDown(input,{key:'Enter'});expect(save).toHaveBeenCalledTimes(1);expect(input).toHaveAttribute('readonly');expect(screen.queryByRole('button',{name:'Cancel'})).toBeNull();await act(async()=>finish!());expect(screen.queryByRole('textbox')).toBeNull();});
it('has accessible read and edit states',async()=>{render(<FileHeader title="Draft" fileTypeLabel="Document" onRename={()=>{}} saveState="error"/>);expect((await axe(document.body,{rules:{region:{enabled:false}}})).violations).toEqual([]);fireEvent.click(screen.getByRole('button',{name:/Rename file/}));expect((await axe(document.body,{rules:{region:{enabled:false}}})).violations).toEqual([]);});

it('forwards native attributes and refs and supports embedded headings',()=>{const ref=React.createRef<HTMLElement>();render(<FileHeader ref={ref} title="Image" fileTypeLabel="Image" id="file" data-test="header" aria-label="Active file" headingLevel={6}/>);expect(ref.current).toHaveAttribute('id','file');expect(screen.getByRole('group',{name:'Active file'})).toHaveAttribute('data-test','header');expect(screen.getByRole('heading',{level:6})).toHaveTextContent('Image');});
it('ignores stale failures when file identity changes during rename',async()=>{let reject:(error:Error)=>void;const save=vi.fn(()=>new Promise<void>((_,fail)=>{reject=fail;}));const {rerender}=render(<FileHeader fileId="a" title="File A" fileTypeLabel="Document" onRename={save}/>);fireEvent.click(screen.getByRole('button',{name:/Rename file/}));fireEvent.change(screen.getByRole('textbox'),{target:{value:'Changed A'}});fireEvent.keyDown(screen.getByRole('textbox'),{key:'Enter'});rerender(<FileHeader fileId="b" title="File B" fileTypeLabel="Image" onRename={()=>{}}/>);fireEvent.click(screen.getByRole('button',{name:/Rename file/}));fireEvent.change(screen.getByRole('textbox'),{target:{value:'Draft B'}});await act(async()=>reject!(new Error('Old failure')));expect(screen.getByRole('textbox')).toHaveValue('Draft B');expect(screen.queryByRole('alert')).toBeNull();});
it('submits the committed composition value',async()=>{const save=vi.fn();render(<FileHeader title="Draft" fileTypeLabel="Document" onRename={save}/>);fireEvent.click(screen.getByRole('button',{name:/Rename file/}));const input=screen.getByRole('textbox');fireEvent.compositionStart(input);fireEvent.change(input,{target:{value:'研究'}});fireEvent.keyDown(input,{key:'Enter',isComposing:true});expect(save).not.toHaveBeenCalled();fireEvent.compositionEnd(input,{data:'研究'});fireEvent.keyDown(input,{key:'Enter'});await waitFor(()=>expect(save).toHaveBeenCalledExactlyOnceWith('研究'));});

it('saves on blur without pulling focus back from the next control',async()=>{const save=vi.fn();render(<><FileHeader title="Draft" fileTypeLabel="Document" onRename={save}/><button>Next</button></>);fireEvent.click(screen.getByRole('button',{name:/Rename file/}));const input=screen.getByRole('textbox');fireEvent.change(input,{target:{value:'New name'}});screen.getByRole('button',{name:'Next'}).focus();await waitFor(()=>expect(save).toHaveBeenCalledExactlyOnceWith('New name'));await waitFor(()=>expect(screen.queryByRole('textbox')).toBeNull());expect(screen.getByRole('button',{name:'Next'})).toHaveFocus();});
