// @vitest-environment jsdom
import * as React from 'react';
import { render, screen, fireEvent, cleanup } from '@testing-library/react';
import { afterEach, expect, it } from 'vitest';
import { TextField } from '../text-field';
afterEach(cleanup);
it('defaults to cutout and keeps error, status and help associated in order',()=>{render(<TextField label="Name" error="Enter a name." status="Check failed." description="Visible to members." pending/>);const input=screen.getByRole('textbox',{name:'Name'});expect(input.closest('.weft-text-field')).toHaveAttribute('data-treatment','cutout');expect(input).toHaveAttribute('aria-invalid','true');expect(input).toHaveAttribute('aria-busy','true');expect(input.getAttribute('aria-describedby')!.split(' ').map(id=>document.getElementById(id)?.textContent)).toEqual(['Enter a name.','Check failed.','Visible to members.']);});
it('supports multiline, native states, caller ids and refs',()=>{const ref=React.createRef<HTMLInputElement|HTMLTextAreaElement>();const {rerender}=render(<TextField ref={ref} id="notes" label="Notes" multiline readOnly defaultValue="Draft"/>);expect(ref.current?.tagName).toBe('TEXTAREA');expect(screen.getByLabelText('Notes')).toHaveAttribute('readonly');expect(screen.getByLabelText('Notes')).toHaveAttribute('data-state','readonly');expect(screen.getByLabelText('Notes')).toHaveAttribute('id','notes');rerender(<TextField label="Date" type="date" disabled/>);expect(screen.getByLabelText('Date')).toBeDisabled();expect(screen.getByLabelText('Date')).toHaveAttribute('type','date');});
it('updates controlled values without managing consumer validation',()=>{function Demo(){const [value,setValue]=React.useState('');return <TextField label="Name" value={value} onChange={e=>setValue(e.target.value)}/>;}render(<Demo/>);fireEvent.change(screen.getByLabelText('Name'),{target:{value:'Studio'}});expect(screen.getByLabelText('Name')).toHaveValue('Studio');});

it('distinguishes read-only visually without replacing its native semantics',()=>{const {rerender}=render(<TextField label="Name" readOnly/>);const field=screen.getByRole('textbox',{name:'Name'});expect(field).not.toBeDisabled();expect(field).toHaveAttribute('readonly');expect(field.closest('.weft-text-field')).toHaveAttribute('data-readonly','true');expect(screen.getByText('Read only')).toHaveAttribute('aria-hidden','true');rerender(<TextField label="Name" readOnly disabled/>);expect(screen.queryByText('Read only')).not.toBeInTheDocument();expect(screen.getByRole('textbox')).toBeDisabled();expect(screen.getByRole('textbox')).toHaveAttribute('data-state','disabled');});

it('omits helper markup and descriptions when no help is supplied',()=>{const {container,rerender}=render(<TextField label="Name"/>);expect(screen.getByRole('textbox')).not.toHaveAttribute('aria-describedby');expect(container.querySelector('[id$="-help"]')).toBeNull();rerender(<TextField label="Name" error="Enter a name."/>);const refs=screen.getByRole('textbox').getAttribute('aria-describedby')!.split(' ');expect(refs).toHaveLength(1);expect(document.getElementById(refs[0])).toHaveTextContent('Enter a name.');expect(container.querySelector('[id$="-help"]')).toBeNull();});

it('does not attach actions to multiline fields',()=>{const {rerender}=render(<TextField label="Notes" multiline action={<button>Send</button>}/>);expect(screen.queryByRole('button')).not.toBeInTheDocument();rerender(<TextField label="Message" action={<button>Send</button>}/>);expect(screen.getByRole('button',{name:'Send'})).toBeInTheDocument();});
