import * as React from 'react';
import { FileHeader, type FileHeaderProps } from '../ui/file-header';
import { FileShell, type FileShellCapabilities } from '../templates/file-shell';
import { FilePresence, FileToolbar, FileMetadata, FileViewFeedback, FileVersionHistory, type FilePanelPurpose, type FileAnnotationMode, type FileViewState, type FileShellPanel, type FileToolbarPurpose } from '../ui/file-shell-controls';
import { fileShellParticipants, fileShellVersions, fileShellRevisions } from '../templates/file-shell.fixture';
import { NavigationActions, type NavigationAction } from '../ui/navigation-actions';
import { Button } from '../ui/button';
import { fileShellIcons, type FileShellIconPurpose } from '../semantics/file-shell-icons';
import './file-header-preview.css';
const commandDefinitions:[string,FileToolbarPurpose][]=[['Paragraph','paragraph'],['Heading 1','heading1'],['Heading 2','heading2'],['Bold','bold'],['Italic','italic'],['Strikethrough','strikethrough'],['Inline code','inlineCode'],['Bullet list','bulletList'],['Numbered list','numberedList'],['Indent list','indent'],['Outdent list','outdent'],['Block quote','quote'],['Code block','codeBlock'],['Horizontal rule','horizontalRule'],['Insert or edit link','link'],['Insert table','table'],['Insert image','image'],['Undo','undo'],['Redo','redo'],['Comment on selection','comments']];
const crowdedPeople=[...fileShellParticipants,...['Sam Rivera','Morgan Park','Taylor Kim','Casey Patel'].map((name,i)=>({id:`extra-${i}`,name,initials:name.split(' ').map(p=>p[0]).join(''),kind:'human' as const}))];
export function ParticipantsPreview({crowded}:{crowded:boolean}){return <FilePresence participants={crowded?crowdedPeople:fileShellParticipants} label="Participants in this file session"/>;}
export function DocumentToolbarPreview({readOnly=false,onCommand}:{readOnly?:boolean;onCommand?:(label:string)=>void}){return <FileToolbar label="Text formatting preview" commands={commandDefinitions.map(([label,purpose])=>({id:purpose,label,purpose,disabled:readOnly,onSelect:()=>onCommand?.(label)}))}/>;}
export function FileHeaderExample({readOnlyExample=false,failRename=false,previewContent,initialPane=null,commentCount,workspaceOnly=false,viewState='ready',populated=false,capabilities:grants,...props}:Partial<FileHeaderProps>&{workspaceOnly?:boolean;readOnlyExample?:boolean;failRename?:boolean;previewContent?:React.ReactNode;commentCount?:number;initialPane?:'comments'|'details'|null;viewState?:FileViewState;populated?:boolean;capabilities?:FileShellCapabilities}){
 const [title,setTitle]=React.useState(props.title??'Product direction');const [notice,setNotice]=React.useState('');const [active,setActive]=React.useState<FilePanelPurpose|null>(initialPane==='details'?'fileInfo':initialPane);const [mode,setMode]=React.useState<FileAnnotationMode|null>('selectElement');const [working,setWorking]=React.useState<string|null>('WIP');const [standing,setStanding]=React.useState('Draft');const [state,setState]=React.useState(viewState);const [reviewed,setReviewed]=React.useState(false);const [versions,setVersions]=React.useState(populated?fileShellVersions:[]);const [revision,setRevision]=React.useState(populated?'revision-2':null);const [revisions,setRevisions]=React.useState(populated?fileShellRevisions:[]);
 const statusName=React.useId();
 const root=React.useRef<HTMLDivElement>(null);const sequence=React.useRef(2);const capabilities=grants??{read:true,write:!readOnlyExample,comment:!readOnlyExample,review:!readOnlyExample};
 React.useEffect(()=>setTitle(props.title??'Product direction'),[props.title]);React.useEffect(()=>setState(viewState),[viewState]);
 const kind=props.fileTypeLabel??'Document';const fileKind:NonNullable<FileHeaderProps['fileKind']>=kind==='HTML file'?'htmlFile':kind==='Spreadsheet'?'spreadsheet':kind==='Presentation'?'presentation':kind==='Image'?'image':'document';
 const item=(label:string,purpose?:FileShellIconPurpose,disabled=false):NavigationAction=>({id:label,label,iconPurpose:purpose,disabled,onSelect:()=>setNotice(`Preview only: ${label}. Application service/dialog is not connected.`)});
 const group=(label:string,purpose:FileShellIconPurpose,children:NavigationAction[]):NavigationAction=>({id:label,label,iconPurpose:purpose,children});
 const fileActions:NavigationAction[]=[...(capabilities.write?[item('New child file','newFile'),item('HTML file — copy agent prompt…','htmlFile'),{...item('Rename','rename'),onSelect:()=>requestAnimationFrame(()=>root.current?.querySelector<HTMLButtonElement>('.weft-file-header-title-edit')?.click())},item('Duplicate','duplicate'),group('Move…','move',[item('Move within this Space…','move'),item('Move to Space…','move',true),item('Copy to Space…','duplicate',true)]),{...item('Working status','workingStatus'),onSelect:()=>setActive('workingStatus')}]:[]),...(capabilities.write&&fileKind==='htmlFile'?[group('Plan lifecycle','moreActions',[item('Pin to Space','pinToSpace'),{...item('Publish plan','publish'),disabled:standing==='Canonical',onSelect:()=>{setStanding('Published');setNotice('Published in local fixture only.');}},{...item('Make canonical','canonical'),disabled:standing!=='Published',onSelect:()=>{setStanding('Canonical');setNotice('Canonical in local fixture only.');}},item('Defer','defer'),item('Archive','archive')])]:[]),group('More','moreActions',[item('Copy link','link'),...(capabilities.review?[{...item('Review','review'),onSelect:()=>setActive('review')}]:[]),{...item('Version history','versionHistory'),onSelect:()=>setActive('versionHistory')}]),...(capabilities.write?[item('Remove…','remove')]:[])];
 const feedback=(content:React.ReactNode)=><FileViewFeedback state={state} error="Fixture load failed. Your file has not changed." onRetry={()=>setState('ready')}>{content}</FileViewFeedback>;
 const rows=[{label:'Name',value:title},{label:'Type',value:kind},{label:'Path',value:`Studio / Research / ${title}`},{label:'Space',value:'Studio'},{label:'Working status',value:working},{label:'Comments',value:commentCount===undefined?null:populated?`${commentCount} total · 2 open · 1 resolved`:`${commentCount} total · open/resolved unknown`},{label:'Standing',value:standing,applicable:fileKind==='htmlFile'},...['File ID','Source format','Plugin ID','Pinned','Lifecycle','Size','Creator','Last editor','Contributors','Current version','Canonical revision','Created','Updated','Last edited','Last reviewed','Content hash','Children','Siblings','Approval ID','Approved by','Approved at','Approved revision','Changes since approval'].map(label=>({label,value:populated?({ 'File ID':'fixture-file-1','Source format':fileKind==='htmlFile'?'html':'markdown','Creator':'Avery Chen','Last editor':'Jordan Lee','Current version':revision,'Canonical revision':'revision-1','Approved revision':'revision-1','Changes since approval':'Yes','Approved by':'Avery Chen','Approved at':'2026-10-01T10:00:00Z','Approval ID':'fixture-approval-1','Last reviewed':reviewed?'Just now (local fixture)':null} as Record<string,React.ReactNode>)[label]??null:null}))];
 const panels:FileShellPanel[]=[{purpose:'comments',label:'Comments',count:commentCount,content:feedback(<>{populated?<><ol><li><strong>Avery Chen · Open</strong><p>Clarify the proposal’s acceptance criteria.</p></li><li><strong>Jordan Lee · Open</strong><p>Check the narrow-screen layout.</p></li><li><strong>Avery Chen · Resolved</strong><p>File identity is consistent.</p></li></ol>{capabilities.comment?<p>Thread creation and replies need the application editor and service.</p>:<p>Read only · commenting unavailable.</p>}</>:<><p>{commentCount?`${commentCount} comments; thread contents not supplied.`:'No comments supplied.'}</p><p>Thread creation is supplied by Avalandra.</p></>}</>)},{purpose:'workingStatus',label:'Working status',content:feedback(<><p>Board status is separate from save status.</p><fieldset disabled={!capabilities.write}><legend className="weft-sr-only">Working status</legend>{['Active','Stale','WIP',null].map(value=><label className="weft-file-status-option" key={value??'clear'}><input type="radio" name={statusName} checked={working===value} onChange={()=>setWorking(value)}/>{value??'No working status'}</label>)}</fieldset>{!capabilities.write&&<p>Read only · status changes unavailable.</p>}</>)},...(capabilities.review?[{purpose:'review' as const,label:'Review',content:feedback(<><p>Review records that you reviewed this revision; it is separate from approval.</p><Button type="button" onClick={()=>setReviewed(true)} disabled={reviewed}>Mark reviewed</Button>{reviewed&&<p role="status">Reviewed in this local fixture only.</p>}</>)}]:[]),{purpose:'fileInfo',label:'File info',content:feedback(<>{populated&&<p role="status">Current revision is later than the approved revision revision-1.</p>}<FileMetadata label="File metadata" rows={rows}/></>)},{purpose:'versionHistory',label:'Version history',content:<FileVersionHistory key={props.fileId??title} versions={versions} revisions={revisions} state={state} error="Could not load fixture versions." onRetry={()=>setState('ready')} canSave={capabilities.write} canRestore={capabilities.write} onSave={async label=>{const n=++sequence.current;setVersions(v=>[...v,{id:`snapshot-${n}`,label:label||null,revisionId:revision??'fixture-revision',createdAt:'Local fixture time',creator:'Preview user'}]);setNotice('Version saved in local fixture only.');}} onRestore={async version=>{const id=`restored-${++sequence.current}`;setRevision(id);setVersions(values=>values.map(v=>({...v,current:false})));setRevisions(values=>[{id,previousId:revision,createdAt:'Local fixture time',creator:'Preview user',current:true},...values.map(r=>({...r,current:false}))]);setNotice(`Local fixture restore of ${version.revisionId} created ${id}. No service was called.`);}}/>}];
 const commands=commandDefinitions.map(([label,purpose])=>({id:purpose,label,purpose,onSelect:()=>purpose==='comments'?setActive('comments'):setNotice(`${label}: host editor required; no file content changed.`)}));
 return <div ref={root}><FileShell showHeader={!workspaceOnly} header={{headingLevel:3,...props,title,fileTypeLabel:kind,fileKind,context:<span>Studio / Research</span>}} capabilities={capabilities} onRename={async next=>{if(failRename)throw Error('Fixture failure');setTitle(next);}} actions={<NavigationActions name={title} items={fileActions} menuLabel="File actions preview"/>} participants={kind==='Document'?crowdedPeople:fileShellParticipants} panels={panels} activePanel={active} onPanelChange={setActive} annotationMode={mode} onAnnotationModeChange={setMode} commands={commands}>{previewContent??<p>File content placeholder</p>}</FileShell><p role="status">{notice}</p></div>;
}
export function FileHeaderStateExample({editableExample=false,failRename=false,readOnlyExample=false,...props}:Partial<FileHeaderProps>&{editableExample?:boolean;failRename?:boolean;readOnlyExample?:boolean}){const [title,setTitle]=React.useState(props.title??'Product direction');React.useEffect(()=>setTitle(props.title??'Product direction'),[props.title]);return <FileHeader headingLevel={3} {...props} title={title} fileTypeLabel={props.fileTypeLabel??'Document'} onRename={!readOnlyExample&&(editableExample||failRename)?async next=>{if(failRename)throw Error('Fixture failure');setTitle(next);}:undefined}/>;}
