/**
 * The specimen page is a committed artifact, and a committed artifact drifts.
 *
 * Everything the tests/contract/ suites measure is read off
 * docs/brand-package/input-specimens.html. If that file can fall behind its
 * generator, the whole harness measures a page nobody edits any more — the same
 * failure as a green gate over a broken surface, one level up.
 *
 * Same gates and the same freshness technique as
 * scripts/__tests__/template-contract.node.mjs, which does this for
 * panel-templates.html.
 */
import { test } from 'node:test';
import assert from 'node:assert/strict';
import { execFileSync } from 'node:child_process';
import { mkdtempSync, readFileSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const ROOT = join(dirname(fileURLToPath(import.meta.url)), '..', '..');
const GENERATED = join(ROOT, 'docs', 'brand-package', 'input-specimens.html');
const GENERATOR = join(ROOT, 'scripts', 'generate-input-specimens.py');
const html = readFileSync(GENERATED, 'utf8');

test('S1: the generated page carries the GENERATED sentinel', () => {
  assert.match(
    html,
    /GENERATED by scripts\/generate-input-specimens\.py/,
    'The committed page has lost its sentinel comment, which is the only thing telling the ' +
      'next reader not to hand-edit it.',
  );
});

test('S2: the generator is deterministic and the committed file is fresh', () => {
  const scratch = mkdtempSync(join(tmpdir(), 'weft-specimens-'));
  const out = join(scratch, 'input-specimens.html');
  execFileSync('python3', [GENERATOR, ROOT, scratch, '--output', out], { stdio: 'pipe' });
  assert.equal(
    readFileSync(out, 'utf8'),
    html,
    'Generator output does not match the committed docs/brand-package/input-specimens.html. ' +
      'Run: npm run specimens',
  );
});

test('S3: the page links the live CSS relatively, and only what a panel receives', () => {
  const links = [...html.matchAll(/<link rel="stylesheet" href="([^"]+)"/g)].map((m) => m[1]);
  assert.deepEqual(
    links,
    ['../../css/weft.css', '../../css/weft-components.css'],
    'The specimen page must link exactly the two files Heddle injects into a panel iframe, ' +
      'relatively, so it always reads the live code. An inlined copy, an absolute path, or a ' +
      'third stylesheet makes the page measure a surface no consumer has.',
  );
});

test('S4: every measurable specimen is addressable without a CSS class', () => {
  // The suites locate specimens by data-spec and by id. Locating by class would
  // couple the tests to the very class names the phases are going to change.
  const specs = new Set([...html.matchAll(/data-spec="([^"]+)"/g)].map((m) => m[1]));
  for (const required of ['boundary', 'geometry', 'geometry-row', 'naming', 'state', 'focus', 'select-chrome']) {
    assert.ok(specs.has(required), `no element carries data-spec="${required}"`);
  }
});

test('S5: the states and boundary matrices are complete', () => {
  const ids = new Set([...html.matchAll(/ id="([^"]+)"/g)].map((m) => m[1]));
  const missing = [];
  // <select> has no readonly in its content model, so that cell does not exist.
  for (const ground of ['paper', 'cream', 'card']) {
    for (const [control, states] of [
      ['input', ['default', 'invalid', 'disabled', 'readonly']],
      ['textarea', ['default', 'invalid', 'disabled', 'readonly']],
      ['select', ['default', 'invalid', 'disabled']],
    ]) {
      for (const state of states) {
        const id = `bnd-${ground}-${control}-${state}`;
        if (!ids.has(id)) missing.push(id);
      }
    }
    if (!ids.has(`bnd-${ground}-ghost-default`)) missing.push(`bnd-${ground}-ghost-default`);
  }
  assert.deepEqual(missing, [], `boundary specimens missing:\n  ${missing.join('\n  ')}`);
});

test('S7: every hint carrying an id is referenced by its control', () => {
  // The plain-CSS layer cannot produce ARIA. What it ships is a markup
  // convention — hint ids of the form `<control-id>-hint` / `-error`, listed in
  // the control's aria-describedby — and a convention nothing checks is a
  // paragraph. Enforced across the whole page rather than on the two specimens
  // that exist to demonstrate it, so wiring one field and not the next fails
  // here instead of downstream.
  const describedBy = new Set(
    [...html.matchAll(/aria-describedby="([^"]+)"/g)].flatMap((m) => m[1].split(/\s+/)),
  );
  const hintIds = [...html.matchAll(/class="weft-field-hint[^"]*"[^>]*\bid="([^"]+)"/g)].map((m) => m[1]);
  assert.ok(hintIds.length >= 3, `expected several identified hints, found ${hintIds.length}`);

  const dangling = hintIds.filter((id) => !describedBy.has(id));
  assert.deepEqual(
    dangling,
    [],
    `Hints carry an id but no control points at them, so they are decoration:\n  ${dangling.join('\n  ')}`,
  );
});

test('S8: hint ids follow the documented pattern, and every reference resolves', () => {
  const ids = new Set([...html.matchAll(/ id="([^"]+)"/g)].map((m) => m[1]));
  const problems = [];
  for (const [, list] of html.matchAll(/aria-describedby="([^"]+)"/g)) {
    for (const ref of list.split(/\s+/)) {
      if (!ids.has(ref)) problems.push(`${ref} is referenced but no element has that id`);
      if (!/-(hint|error)$/.test(ref)) problems.push(`${ref} does not end in -hint or -error`);
    }
  }
  assert.deepEqual(problems, [], `Description wiring is broken:\n  ${problems.join('\n  ')}`);
});

test('S8a: an error element carries an -error id, and a hint carries -hint', () => {
  // S8 checked that every reference resolves and is named to the convention.
  // It never bound the element's ROLE to its id, so an `.is-error` span could
  // wear a `-hint` id — an error masquerading as a hint, in the page that
  // teaches the convention, with S8b's ordering check never firing because only
  // one id was present. Exactly the shape this suite exists to refuse.
  const problems = [];
  for (const [, cls, id] of html.matchAll(/class="(weft-field-hint[^"]*)"[^>]*\bid="([^"]+)"/g)) {
    const isError = /\bis-error\b/.test(cls);
    if (isError && !id.endsWith('-error')) problems.push(`#${id} is an error but its id is not -error`);
    if (!isError && !id.endsWith('-hint')) problems.push(`#${id} is a hint but its id is not -hint`);
  }
  assert.deepEqual(problems, [], `Hint and error ids must match their role:\n  ${problems.join('\n  ')}`);
});

test('S8b: where both are present, the error id comes first (amendment A5)', () => {
  // ORDER IS THE WHOLE RULE, so order is what is asserted. S7 and S8 check that
  // the ids exist, resolve, and are named correctly — all three of which the
  // WRONG order satisfies perfectly, which is exactly how this shipped
  // backwards: every guard around the rule was true and none was about it.
  const problems = [];
  for (const [, list] of html.matchAll(/aria-describedby="([^"]+)"/g)) {
    const refs = list.split(/\s+/).filter(Boolean);
    const errorAt = refs.findIndex((r) => r.endsWith('-error'));
    const hintAt = refs.findIndex((r) => r.endsWith('-hint'));
    if (errorAt === -1 || hintAt === -1) continue;  // only one kind present
    if (errorAt > hintAt) {
      problems.push(`"${list}" lists the help text before the error`);
    }
  }
  assert.deepEqual(
    problems,
    [],
    'Amendment A5: one ordered aria-describedby list, error id first. A field in error has ' +
      'one urgent thing to say and one background thing.\n  ' + problems.join('\n  '),
  );
});

test('S12: every in-page link has a target', () => {
  // The skip-link specimen pointed at #naming-end, which did not exist — so the
  // page demonstrated a broken skip link while the focus test, which only
  // checked that the link reveals on focus, stayed green. Revealing is half the
  // pattern; landing somewhere is the other half.
  const ids = new Set([...html.matchAll(/ id="([^"]+)"/g)].map((m) => m[1]));
  const dead = [...html.matchAll(/href="#([^"]+)"/g)].map((m) => m[1]).filter((t) => !ids.has(t));
  assert.deepEqual(dead, [], `in-page links with no target: ${dead.map((d) => '#' + d).join(', ')}`);
});

test('S9: a required marker is real text and its control carries the attribute', () => {
  // Decision 4. A bare glyph lands in the accessible name as punctuation while
  // `required` stays false — observed name "RETENTION*", required false.
  const markers = [...html.matchAll(/<span class="weft-req">([^<]*)<\/span>/g)].map((m) => m[1]);
  assert.ok(markers.length > 0, 'the page has no required marker to check');
  const glyphs = markers.filter((text) => !/[a-z]/i.test(text));
  assert.deepEqual(glyphs, [], `Required markers that are punctuation rather than text: ${glyphs.join(', ')}`);

  // Every label containing a marker must point at a control declaring `required`.
  for (const match of html.matchAll(/<label class="weft-field-label" for="([^"]+)">([\s\S]*?)<\/label>/g)) {
    const [, forId, inner] = match;
    if (!inner.includes('weft-req')) continue;
    const control = new RegExp(`<(?:input|select|textarea)[^>]*\\bid="${forId}"[^>]*>`).exec(html);
    assert.ok(control, `the marked label points at #${forId}, which does not exist`);
    assert.match(
      control[0],
      /\brequired\b/,
      `#${forId} is marked required in its label but the control does not declare the attribute`,
    );
  }
});

test('S10: no text-entry control is named by aria-label', () => {
  // The ladder sanctions aria-label for icon-only controls and nothing else. A
  // rule stated in doctrine and broken by the page that demonstrates it teaches
  // the breach, so this is enforced across every input, select and textarea on
  // the page — including the measurement specimens, which are not exempt. If
  // they needed to be, the rule would be wrong.
  const offenders = [];
  for (const [, tag, attrs] of html.matchAll(/<(input|select|textarea)\b([^>]*)>/g)) {
    if (!/\baria-label="/.test(attrs)) continue;
    const id = /\bid="([^"]+)"/.exec(attrs)?.[1] ?? '(no id)';
    offenders.push(`<${tag} id="${id}">`);
  }
  assert.deepEqual(
    offenders,
    [],
    'These controls are named by aria-label, which the naming ladder sanctions only for ' +
      `icon-only controls. Use a real <label>, hidden with .weft-sr-only if the surface cannot ` +
      `carry a visible one:\n  ${offenders.join('\n  ')}`,
  );
});

test('S11: the rendered reference page teaches the shipped input contract', () => {
  // docs/brand-package/design-system.html is self-contained — it carries its own
  // copy of the CSS rather than linking css/ — so it can describe one contract
  // in prose while rendering another. It did, twice, and the second time was
  // because the first version of THIS GUARD was too weak: it matched one literal
  // marker shape and the presence of two token names, so it passed a page that
  // still had `outline: none` on focus, an uppercase legend, and a stale
  // syntax-highlighted code sample. A guard that only checks the thing you
  // happened to fix will pass the thing you happened to miss.
  //
  // Each check below is therefore aimed at a CONTRACT, and at every form the
  // page can express it in: rendered markup, embedded CSS, and escaped samples.
  const page = readFileSync(join(ROOT, 'docs', 'brand-package', 'design-system.html'), 'utf8');
  // TWO views of the page, and both are needed. Stripping tags turns the escaped
  // code samples into real markup, which is the only way to inspect them — but it
  // also destroys the RENDERED markup, so a check run only against the decoded
  // copy silently skips every real specimen. The first version of this guard did
  // exactly that and passed a bare asterisk sitting in the page.
  const decoded = page
    .replace(/<[^>]+>/g, '')
    .replace(/&lt;/g, '<').replace(/&gt;/g, '>').replace(/&quot;/g, '"').replace(/&amp;/g, '&');
  const views = [
    ['rendered markup', page],
    ['a code sample', decoded],
  ];
  const problems = [];

  // The focus ring has two carriers. One alone is deletable.
  const focusRule = /:focus-visible\s*\{([^}]*)\}/.exec(page)?.[1] ?? '';
  if (!/outline:\s*\d/.test(focusRule)) problems.push('the focus rule paints no outline');
  if (!/box-shadow:/.test(focusRule)) problems.push('the focus rule paints no box-shadow');
  if (/outline:\s*none/.test(focusRule)) problems.push('the focus rule still resets the outline');

  // Field labels and legends are sentence case: an uppercase transform rewrites
  // the accessible name. Every OTHER uppercase on the page is legitimate.
  for (const selector of ['.field-label', 'legend']) {
    const rule = new RegExp(`${selector.replace('.', '\\.')}\\s*\\{([^}]*)\\}`).exec(page)?.[1] ?? '';
    if (/text-transform:\s*uppercase/.test(rule)) {
      problems.push(`${selector} still uppercases, which rewrites the accessible name`);
    }
  }

  // The boundary tokens, in the embedded copy.
  for (const token of ['--weft-control-border', '--weft-control-fill']) {
    if (!page.includes(token)) problems.push(`the embedded CSS does not use ${token}`);
  }

  for (const [where, view] of views) {
    // The required marker is a word, never punctuation.
    for (const [, marker] of view.matchAll(/class="req">([^<]*)</g)) {
      if (!/[a-z]/i.test(marker)) {
        problems.push(`in ${where}, a marker reads ${JSON.stringify(marker)} rather than a word`);
      }
    }
    // And a control whose label says required must actually be required. Paired
    // by `for`/`id` rather than by proximity: the first attempt bounded the
    // search by the next closing tag within 400 characters, which a <select>
    // full of <option>s comfortably outruns — so it silently checked nothing for
    // exactly the specimen that was wrong.
    for (const [, forId, inner] of view.matchAll(/<label\b[^>]*\bfor="([^"]+)"[^>]*>([\s\S]*?)<\/label>/g)) {
      if (!inner.includes('class="req"')) continue;
      const control = new RegExp(`<(?:input|select|textarea)\\b[^>]*\\bid="${forId}"[^>]*>`).exec(view);
      if (!control) {
        problems.push(`in ${where}, a label marked required points at #${forId}, which does not exist`);
      } else if (!/\brequired\b/.test(control[0])) {
        problems.push(`in ${where}, #${forId} is marked required in its label but the control is not`);
      }
    }
  }

  // The describedby convention, in both views. S11 claimed this page teaches the
  // shipped contract while never checking the one rule most likely to rot in it.
  for (const [where, view] of views) {
    for (const [, cls, id] of view.matchAll(/class="[^"]*\b(field-hint[^"]*)"[^>]*\bid="([^"]+)"/g)) {
      const isError = /\bis-error\b/.test(cls);
      if (isError && !id.endsWith('-error')) {
        problems.push(`in ${where}, #${id} is an error but its id is not -error`);
      }
    }
    const idsHere = new Set([...view.matchAll(/\bid="([^"]+)"/g)].map((m) => m[1]));
    for (const [, list] of view.matchAll(/aria-describedby="([^"]+)"/g)) {
      const refs = list.split(/\s+/).filter(Boolean);
      const e = refs.findIndex((r) => r.endsWith('-error'));
      const h = refs.findIndex((r) => r.endsWith('-hint'));
      if (e !== -1 && h !== -1 && e > h) {
        problems.push(`in ${where}, "${list}" lists the help text before the error`);
      }
      // A reference that resolves to nothing describes nothing. Renaming the
      // element and not its reference passes both the role check and the order
      // check, because neither looks at whether the target exists — which is how
      // the probe for this guard slipped through the first time.
      for (const ref of refs) {
        if (!idsHere.has(ref)) problems.push(`in ${where}, aria-describedby names #${ref}, which does not exist`);
      }
    }
  }

  assert.deepEqual(problems, [], `docs/brand-package/design-system.html has drifted:\n  ${problems.join('\n  ')}`);
});

test('S6: every control on the page has an accessible name, except where absence is the point', () => {
  // Mirrors T2-c in the template contract. The exception is deliberate and
  // narrow: #nm-placeholder exists precisely to be a control with no name, and
  // is the case the tool-based check passes.
  const NAMELESS_BY_DESIGN = new Set(['nm-placeholder']);
  const controls = [...html.matchAll(/<(input|select|textarea)\b([^>]*)>/g)];
  assert.ok(controls.length > 30, 'the specimen page has suspiciously few controls');

  const unnamed = [];
  for (const [, , attrs] of controls) {
    const id = /\bid="([^"]+)"/.exec(attrs)?.[1] ?? '(no id)';
    if (NAMELESS_BY_DESIGN.has(id)) continue;
    const hasAriaLabel = /\baria-label="/.test(attrs);
    const hasLabelFor = id !== '(no id)' && html.includes(`for="${id}"`);
    const wrappedByLabel = new RegExp(`<label[^>]*>(?:(?!</label>)[\\s\\S])*id="${id}"`).test(html);
    if (!hasAriaLabel && !hasLabelFor && !wrappedByLabel) unnamed.push(id);
  }
  assert.deepEqual(unnamed, [], `controls with no naming route:\n  ${unnamed.join('\n  ')}`);
});
