/**
 * The specimen page is a committed artifact, and a committed artifact drifts.
 *
 * Everything the tests/contract/ suites measure is read off
 * docs/brand-package/input-specimens.html. If that file can fall behind its
 * generator, the whole harness measures a page nobody edits any more — the same
 * failure as a green gate over a broken surface, one level up.
 *
 * Same gates and the same freshness technique as
 * scripts/__tests__/template-contract.node.mjs, which does this for
 * panel-templates.html.
 */
import { test } from 'node:test';
import assert from 'node:assert/strict';
import { execFileSync } from 'node:child_process';
import { mkdtempSync, readFileSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const ROOT = join(dirname(fileURLToPath(import.meta.url)), '..', '..');
const GENERATED = join(ROOT, 'docs', 'brand-package', 'input-specimens.html');
const GENERATOR = join(ROOT, 'scripts', 'generate-input-specimens.py');
const html = readFileSync(GENERATED, 'utf8');

test('S1: the generated page carries the GENERATED sentinel', () => {
  assert.match(
    html,
    /GENERATED by scripts\/generate-input-specimens\.py/,
    'The committed page has lost its sentinel comment, which is the only thing telling the ' +
      'next reader not to hand-edit it.',
  );
});

test('S2: the generator is deterministic and the committed file is fresh', () => {
  const scratch = mkdtempSync(join(tmpdir(), 'weft-specimens-'));
  const out = join(scratch, 'input-specimens.html');
  execFileSync('python3', [GENERATOR, ROOT, scratch, '--output', out], { stdio: 'pipe' });
  assert.equal(
    readFileSync(out, 'utf8'),
    html,
    'Generator output does not match the committed docs/brand-package/input-specimens.html. ' +
      'Run: npm run specimens',
  );
});

test('S3: the page links the live CSS relatively, and only what a panel receives', () => {
  const links = [...html.matchAll(/<link rel="stylesheet" href="([^"]+)"/g)].map((m) => m[1]);
  assert.deepEqual(
    links,
    ['../../css/weft.css', '../../css/weft-components.css'],
    'The specimen page must link exactly the two files Heddle injects into a panel iframe, ' +
      'relatively, so it always reads the live code. An inlined copy, an absolute path, or a ' +
      'third stylesheet makes the page measure a surface no consumer has.',
  );
});

test('S4: every measurable specimen is addressable without a CSS class', () => {
  // The suites locate specimens by data-spec and by id. Locating by class would
  // couple the tests to the very class names the phases are going to change.
  const specs = new Set([...html.matchAll(/data-spec="([^"]+)"/g)].map((m) => m[1]));
  for (const required of ['boundary', 'geometry', 'geometry-row', 'naming', 'state', 'focus', 'select-chrome']) {
    assert.ok(specs.has(required), `no element carries data-spec="${required}"`);
  }
});

test('S5: the states and boundary matrices are complete', () => {
  const ids = new Set([...html.matchAll(/ id="([^"]+)"/g)].map((m) => m[1]));
  const missing = [];
  // <select> has no readonly in its content model, so that cell does not exist.
  for (const ground of ['paper', 'cream', 'card']) {
    for (const [control, states] of [
      ['input', ['default', 'invalid', 'disabled', 'readonly']],
      ['textarea', ['default', 'invalid', 'disabled', 'readonly']],
      ['select', ['default', 'invalid', 'disabled']],
    ]) {
      for (const state of states) {
        const id = `bnd-${ground}-${control}-${state}`;
        if (!ids.has(id)) missing.push(id);
      }
    }
    if (!ids.has(`bnd-${ground}-ghost-default`)) missing.push(`bnd-${ground}-ghost-default`);
  }
  assert.deepEqual(missing, [], `boundary specimens missing:\n  ${missing.join('\n  ')}`);
});

test('S6: every control on the page has an accessible name, except where absence is the point', () => {
  // Mirrors T2-c in the template contract. The exception is deliberate and
  // narrow: #nm-placeholder exists precisely to be a control with no name, and
  // is the case the tool-based check passes.
  const NAMELESS_BY_DESIGN = new Set(['nm-placeholder']);
  const controls = [...html.matchAll(/<(input|select|textarea)\b([^>]*)>/g)];
  assert.ok(controls.length > 30, 'the specimen page has suspiciously few controls');

  const unnamed = [];
  for (const [, , attrs] of controls) {
    const id = /\bid="([^"]+)"/.exec(attrs)?.[1] ?? '(no id)';
    if (NAMELESS_BY_DESIGN.has(id)) continue;
    const hasAriaLabel = /\baria-label="/.test(attrs);
    const hasLabelFor = id !== '(no id)' && html.includes(`for="${id}"`);
    const wrappedByLabel = new RegExp(`<label[^>]*>(?:(?!</label>)[\\s\\S])*id="${id}"`).test(html);
    if (!hasAriaLabel && !hasLabelFor && !wrappedByLabel) unnamed.push(id);
  }
  assert.deepEqual(unnamed, [], `controls with no naming route:\n  ${unnamed.join('\n  ')}`);
});
